import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  wiki: [
    "index",
    {
      type: "category",
      label: "Administración de Servidores",
      link: { type: "doc", id: "servidores/index" },
      items: [{ type: "autogenerated", dirName: "servidores" }],
    },
    {
      type: "category",
      label: "Estación de Trabajo",
      link: { type: "doc", id: "workstation/index" },
      items: [{ type: "autogenerated", dirName: "workstation" }],
    },
    {
      type: "category",
      label: "Notas sobre Cloud",
      link: { type: "doc", id: "cloud/index" },
      items: [{ type: "autogenerated", dirName: "cloud" }],
    },
  ],
};

export default sidebars;
